baseURL       = "https://seekerskeptic.netlify.com/"
languageCode  = "en-gb"
title         = "The Seeker and the Skeptic"
theme         = "sas"
enableGitInfo = true

[params]
description = "A podcast about fringe ideas"
author      = "Cat and Rebecca"
youtubeUrl  = "https://www.youtube.com/channel/UCsAvzf-XD53ebVyH1liNZtQ"
videoUrl    = "https://www.youtube.com/watch?v=ncumD8VozLQ"
podcastUrl  = "https://plinkhq.com/i/1437772161"
twitterUrl  = "https://twitter.com/seekerskeptic"

[params.GoogleAnalytics]
id = "UA-XXX-2"

